"""Remove the incompatible nuScenes detection head from a BEVFusion checkpoint."""

import argparse
from pathlib import Path

import torch


def normalized_key(key):
    return str(key).replace("module.", "", 1)


def removal_reason(key):
    """Return why a source tensor is incompatible with the UAV model."""
    normalized = normalized_key(key)
    if normalized.startswith("heads.object.") or ".heads.object." in normalized:
        return "10-class detection head"

    # UAV image resolution, depth bins and BEV bounds differ from nuScenes.
    # Geometry tensors must be regenerated by the new model.  The final
    # depthnet convolution also changes shape because D changes.
    vtransform_prefix = "encoders.camera.vtransform."
    if normalized.startswith(vtransform_prefix):
        suffix = normalized[len(vtransform_prefix) :]
        if suffix in ("dx", "bx", "nx", "frustum"):
            return "camera geometry tensor"
        if suffix.startswith("depthnet.6."):
            return "depth-bin prediction layer"
    return None


def is_object_head_key(key):
    # Kept as a small public helper for existing user scripts.
    normalized = str(key).replace("module.", "", 1)
    return normalized.startswith("heads.object.") or ".heads.object." in normalized


def main():
    parser = argparse.ArgumentParser(
        description="Keep pretrained encoders/fuser/decoder and drop the 10-class head"
    )
    parser.add_argument("input", help="Original nuScenes BEVFusion checkpoint")
    parser.add_argument("output", help="Filtered checkpoint for UAV fine-tuning")
    args = parser.parse_args()

    input_path = Path(args.input).expanduser()
    output_path = Path(args.output).expanduser()
    checkpoint = torch.load(str(input_path), map_location="cpu")
    state_dict = checkpoint.get("state_dict", checkpoint)
    kept = {}
    removed = []
    reasons = {}
    for key, value in state_dict.items():
        reason = removal_reason(key)
        if reason is not None:
            removed.append(key)
            reasons[reason] = reasons.get(reason, 0) + 1
        else:
            kept[key] = value

    if "state_dict" in checkpoint:
        checkpoint["state_dict"] = kept
        checkpoint.pop("optimizer", None)
        checkpoint.pop("optimizer_states", None)
        if isinstance(checkpoint.get("meta"), dict):
            checkpoint["meta"].pop("CLASSES", None)
        output_checkpoint = checkpoint
    else:
        output_checkpoint = kept
    output_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(output_checkpoint, str(output_path))
    print("Input parameters : {}".format(len(state_dict)))
    print("Kept parameters  : {}".format(len(kept)))
    print("Removed tensors   : {}".format(len(removed)))
    for reason, count in sorted(reasons.items()):
        print("  {:>4d}  {}".format(count, reason))
    print("Saved to         : {}".format(output_path))


if __name__ == "__main__":
    main()
